name: CI/CD

on: [push]

jobs:
  cicd:
    name: Deploy stack to AWS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - stack-name: portfolio-dev
            template-path: "cloudformation/templates/portfolio-dev.yml"

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: Validate CloudFormation template
      run: |
        aws cloudformation validate-template \
          --template-body "file://${{ matrix.template-path }}"

    - name: Run Checkov action
      id: checkov
      uses: bridgecrewio/checkov-action@master
      with:
        directory: cloudformation/templates/
        quiet: true
        framework: cloudformation

    # Work out a better solution to deal with ROLLBACK_COMPLETE states, etc
    - name: Delete existing stack
      continue-on-error: true
      run: |
        aws cloudformation delete-stack \
          --stack-name ${{ matrix.stack-name }}

    - name: Wait for deletion to complete
      continue-on-error: true
      run: |
        aws cloudformation wait stack-delete-complete \
          --stack-name ${{ matrix.stack-name }}

    - name: Deploy stack
      run: |
        aws cloudformation deploy \
          --stack-name ${{ matrix.stack-name }} \
          --template-file "${{ matrix.template-path }}" \
          --no-fail-on-empty-changeset
