name: CI/CD

on: [push]

jobs:
  cicd:
    name: Deploy stack to AWS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        template: ["portfolio-dev.yml"]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: Validate CloudFormation template
      run: |
        aws cloudformation validate-template --template-body "file://cloudformation/templates/${{ matrix.template }}"
